var myCar=new Image();
myCar.src="img/Pink-Car.png"
var myCar2=new Image()
myCar2.src="img/yellow.png"
var enemyCars=new Image()
enemyCars.src="img/blue.png"
var valueArr=new Array()
var valueCounter=0
let roadIm=new Image()
roadIm.src="img/road.png"
var bonus=new Image()
bonus.src="img/money.png"
var bonusValueArr= new Array()
var bonusValue=0
