var img_array=["img/r.png","img/green.png","img/w.png"];
var myCar=new Image();
myCar.src=img_array[sessionStorage.xmodel]
var myCar2=new Image()
myCar2.src="img/yellow.png"
var enemyCars=new Image()
enemyCars.src="img/blue.png"
var valueArr=new Array()
var valueCounter=0
let roadIm=new Image()
roadIm.src="img/road.png"
